CREATE TABLE user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE upload (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL REFERENCES user(id),
  name VARCHAR(256) NOT NULL,
  size BIGINT NOT NULL,
  uploaded_at BIGINT NOT NULL,
  path VARCHAR(256) NOT NULL,
  hash VARCHAR(256) NOT NULL,
  mime VARCHAR(256) NOT NULL
);

CREATE TABLE thumbnail (
  id BIGINT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES user(id),
  size BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  path VARCHAR(256) NOT NULL,
  hash VARCHAR(256) NOT NULL,
  mime VARCHAR(256) NOT NULL
);
