CREATE TABLE photo (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL REFERENCES user(id),
  name VARCHAR(256) NOT NULL,
  size BIGINT NOT NULL,
  uploaded_at BIGINT NOT NULL,
  path VARCHAR(256) NOT NULL,
  hash VARCHAR(256) NOT NULL
);
