CREATE TABLE user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE journal_entry (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  entry VARCHAR(1024) NOT NULL,
  user_id BIGINT NOT NULL REFERENCES user(id),
  date BIGINT
);
